import ProviderRedux from "@/redux/provider";
import "./globals.scss";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderRedux>{children}</ProviderRedux>
      </body>
    </html>
  );
}
